

#### path of spatialAPA 
spatialAPA_path: "/path/to/spatialAPA"
#### input and output path which include fastqs
IN_PATH: "/path/to/inputfiles"
#### bed file containing UTR region (see https://github.com/LuChenLab/SCAPE)
bed_file: "/path/to/GRCh38_utr.bed"
#### path of SCAPE tool which should be pre-install(https://github.com/LuChenLab/SCAPE)
scape_path: "/path/to/SCAPE"
#### path to project-sample file containing two columns sep by tab(project samplename)
gse_gsm_list: "/path/to/gse_gsm.txt"
#### file of stop codon for calculating WUL
stop_codon_file: "/path/to/GRCh38.v44.stop_codon.tsv"
#### gtf file path
gtf_file: "/path/to/GRCh38.gtf"
#### file containing ENSG (rowname) and gene symbol ("Symbol" column)
ensg_symbol: "/path/to/ensg_symbol_type.txt"
#### index path for spaceranger
REF_APP: "/path/to/hg38_gencodev44"
#### slide serial number (see spaceranger params)
SLIDE: "--unknown-slide visium-1"
#### CPU core used for running spaceranger (default 64 CPU cores)
CORE: 64
#### memory used for running spaceranger (default 64G)
MEM: 64

#### specified sample name and image path
samples:
  - GSM: sample1
    image: "/path/to/image1.png"
    darkimage: null
    loupe: null
