

IN_PATH: "/public/home/jiangzh/projects/sc_apa/database/SCAPE_res"
bed_file: "/public/home/jiangzh/projects/sc_apa/GRCh38_utr.bed"
scape_path: "/public/home/jiangzh/biosoft/SCAPE"
gse_gsm_list: "/public/home/jiangzh/projects/sc_apa/gse_gsm_101.txt"
scape_preprocess_1: "/public/home/jiangzh/projects/sc_apa/database/scape_preprocess_annot_apa.r"
scape_preprocess_2: "/public/home/jiangzh/projects/sc_apa/database/scape_preprocess_add.r"
scape_calculate_len: "/public/home/jiangzh/projects/sc_apa/calculate_apa_new.py"
scape_rule: "/public/home/jiangzh/projects/sc_apa/run_scape.rule.py"
stop_codon_file: "/public/home/jiangzh/projects/sc_apa/GRCh38.v44.stop_codon.tsv"

